spring:
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
 #   username: sa
 #   password: password
  # mybatis관련 설정
mybatis:
  mapper-location: "classpath:mybatis/mappers/*.xml"
  type-aliases-package: "com.example.mybatis.model"
  configuration:
    map-underscore-to-camel-case: true  #snake_case - camelCase, PascalCase
